# Generated by Django 5.0.2 on 2024-04-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_alter_customuser_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='private_keys/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_key',
            field=models.FileField(blank=True, null=True, upload_to='public_keys/'),
        ),
    ]
