# Generated by Django 5.0.2 on 2024-04-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_alter_customuser_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
